In [ ]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vec = tf.constant([10, 10])
vec.ndim

1

In [ ]:
matrix = tf.constant([[10, 10] for x in range(2)])
matrix.ndim

2

In [ ]:
matrix = tf.constant([[10, 10] for x in range(2)], dtype=tf.float16)
matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10., 10.],
       [10., 10.]], dtype=float16)>

In [ ]:
tensor = tf.constant([[[k + j + i for k in range(2)] for j in range(2)] for i in range(2)])
tensor.ndim

3

In [ ]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#won't work
#unchangeable_tensor[0].assign(7)

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [ ]:
#Shuffle a tensor
not_shuffled = tf.constant([[10, 7],
                            [3,4],
                            [2,5]])
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
import numpy as np
np_A = np.arange(1, 25, dtype=np.int32)
np_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
tf_A = tf.constant(np_A, shape=(3, 8))
tf_A

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [ ]:
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor), tf.size(rank_4_tensor).numpy(), rank_4_tensor.dtype

(TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>,
 120,
 tf.float32)

In [ ]:
rank_4_tensor[:1, :1, :1, :], rank_4_tensor[:1, :1, :1, :].numpy()

(<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>,
 array([[[[0., 0., 0., 0., 0.]]]], dtype=float32))

In [ ]:
rank_2_tensor = tf.constant([[3, 7],
                             [1, 3]])
#get last item from every collumn in tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 3], dtype=int32)>

In [ ]:
#... gets every dimention in one (replaces :, :, etc.)
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [7]],

       [[1],
        [3]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [7]],

       [[1],
        [3]]], dtype=int32)>

In [ ]:
tensor = tf.constant([[3, 7],
                      [1, 3]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 17],
       [11, 13]], dtype=int32)>

In [ ]:
tensor+=3
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6, 10],
       [ 4,  6]], dtype=int32)>

In [ ]:
tf.math.multiply(tensor, 10)
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 60, 100],
       [ 40,  60]], dtype=int32)>

In [ ]:
tf.linalg.matmul(rank_2_tensor, rank_2_tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 42],
       [ 6, 16]], dtype=int32)>

In [ ]:
rank_2_tensor @ rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 42],
       [ 6, 16]], dtype=int32)>

In [ ]:
tensor_1 = tf.constant([[3, 7],
                        [1, 3],
                        [2, 8]])
tensor_2 = tf.constant([[3, 7],
                        [1, 3],
                        [2, 8]])
# won't work becouse of the shape
# tensor_1 @ tensor_2

# to make matrix multip work the shape of matrix must be flipped in one of the matrix

# slow methods:
# tensor_2 = tf.constant([[3, 7, 1], [2, 8, 3]])
# or
# tensor_2 = tf.reshape(tensor_2, shape=(2, 3))
# tensor_1 @ tensor_2

# normal method:
print(tensor_1 @ tf.reshape(tensor_2, shape=(2, 3)))

# or
print(tf.transpose(tensor_1) @ tensor_2)
#note: the shape of this multipycation is different becouse shape of the right-site tensor is directed by outer sizes of both left-side tensors
# shape is different not becouse of transpose but becouse we do transpose on 1st tensor

# note 2: transpose and reshape are different in that reshape is random and transpose is not

tf.Tensor(
[[30 35 59]
 [12 13 25]
 [30 30 66]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 14  40]
 [ 40 122]], shape=(2, 2), dtype=int32)


In [ ]:
# min, max, mean, sum
tf.reduce_min(tensor_1), tf.reduce_max(tensor_1), tf.reduce_mean(tensor_1), tf.reduce_sum(tensor_1)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=int32, numpy=24>)

In [ ]:
# standart deviation and variance using math
tf.math.reduce_std(tf.cast(tensor_1, dtype=tf.float32))
tf.math.reduce_variance(tensor_1)

<tf.Tensor: shape=(), dtype=float32, numpy=2.5819888>

In [ ]:
# variance and normal distribution using tfp
import tensorflow_probability as tfp
tfp.stats.variance(tensor_1)
tfp.distributions.Normal(tensor_1, scale=tensor_2)

<tfp.distributions.Normal 'Normal' batch_shape=[3, 2] event_shape=[] dtype=int32>

In [ ]:
tf.random.set_seed(42)
tensor_3 = tf.random.uniform(shape=[50])
tensor_3

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# min and max using argx
tensor_3[tf.argmin(tensor_3)], tensor_3[tf.argmax(tensor_3)]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [ ]:
# positional min and max
tensor_4 = tf.constant([[2, 20, 30, 3, 6], [3, 11, 16, 1, 8], [14, 45, 23, 5, 27]])
tf.math.argmax(tensor_4, 0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 2, 0, 2, 2])>

In [ ]:
bad_tensor = tf.constant(tf.random.uniform(shape=[10]), shape=[1, 1, 1, 10])
good_tensor = tf.squeeze(bad_tensor)
bad_tensor, good_tensor

(<tf.Tensor: shape=(1, 1, 1, 10), dtype=float32, numpy=
 array([[[[0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
           0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ]]]],
       dtype=float32)>,
 <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
        0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ],
       dtype=float32)>)

In [ ]:
one_hot_list = [0, 1, 2, 3]
tf.one_hot(one_hot_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(one_hot_list, depth=4, on_value=':)', off_value=':|')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b':)', b':|', b':|', b':|'],
       [b':|', b':)', b':|', b':|'],
       [b':|', b':|', b':)', b':|'],
       [b':|', b':|', b':|', b':)']], dtype=object)>